apiVersion: v1
kind: Secret
metadata:
  name: local-lco-earth-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE/zCCA+egAwIBAgISBuFkVwZJwEXxInX35eMqosthMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTIwHhcNMjUwOTEzMTgxOTI1WhcNMjUxMjEyMTgxOTI0WjAcMRowGAYDVQQD
    DBEqLmxvY2FsLmxjby5lYXJ0aDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBALVprS7GXUAXkZLKlTcqvNgvN5y3DZ57J1LGu9/+hiSFYmI6vurU8Att6Qai
    Uky+/9cMVa+yTU7DPd590J3CnarNl8tUtPMdV0OvMcULiqUhmE1l4gOg09E7k++X
    wLPDd6IDqdArpuR7d1x3hODnSe4RzOZk/3ym5dNtl1fS+iLzS1+ARwOgerpCrXlr
    7wunH/7KMmhq9KjqluvO4KKezkz+i51M8AxCizeaTw+GpN5bvQ3/brGYPc6ciKKK
    vs50TxyGu2DoIrMEMjrNNf05I/ZNBGYIv8eygtW+CDdlS1iGtLkaq3zw2/YZKFjc
    nDVUhjZgrb7sCobzhObtYLXDX2UCAwEAAaOCAiIwggIeMA4GA1UdDwEB/wQEAwIF
    oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAd
    BgNVHQ4EFgQU4hQsOoJ5jpcQ2kWoE6Yf48kdUnEwHwYDVR0jBBgwFoAUALUp8i2O
    bzHom0yteD763OkM0dIwMwYIKwYBBQUHAQEEJzAlMCMGCCsGAQUFBzAChhdodHRw
    Oi8vcjEyLmkubGVuY3Iub3JnLzAcBgNVHREEFTATghEqLmxvY2FsLmxjby5lYXJ0
    aDATBgNVHSAEDDAKMAgGBmeBDAECATAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8v
    cjEyLmMubGVuY3Iub3JnLzk4LmNybDCCAQUGCisGAQQB1nkCBAIEgfYEgfMA8QB3
    AMz7D2qFcQll/pWbU87psnwi6YVcDZeNtql+VMD+TA2wAAABmUSDPnQAAAQDAEgw
    RgIhALdaeUqDJAeTK8xMmSczXzAIlCqFeb3aJgN14f7iw0ryAiEAqCSd7XRRgGyY
    0t9YafEHZ56Tui5a+bV6HK+vF8wdrCEAdgAaBP9J0FQdQK/2oMO/8djEZy9O7O4j
    QGiYaxdALtyJfQAAAZlEgz56AAAEAwBHMEUCIQDNQsVs3GPDYVme0Gax7+MYgQGF
    RClaju0g8Wx/e4awBwIgaI1W67y+pQOCVlKetihAOqOjHpqFYmOcEJkRjT4tee4w
    DQYJKoZIhvcNAQELBQADggEBALk7R6ZnJx3Tjv3XVTQGP4VbhFUqxL8R5sLICHa+
    vKsqCCnP8WCdh6wyLiJrrLpQlevC/XIJTFAEY6HDWTu7HQoMBa70MCLPbpx3MnUC
    2MKYv+j7BmfzMUk2uXd7qbR/3kMFdFA2u3A5QGNWD8ic5m/8E/OgJUGz9fku54Vy
    FKkQqGbQQ6l9/IMqNBlrk+cQqU5iHHCbFNa6X1WpWrtjkahRo8fK9eOVrvRBGN4g
    SqKdq+vTTIfjmrgpN1HT08txIyMXVV6i5kcZjEtj+9AyXOBHsKqj4y/0UmoftthL
    3ZdyptCP7My/J9ZFaf36HD9A4DITqWz3qXzMCT8PVZfMX8w=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBjCCAu6gAwIBAgIRAMISMktwqbSRcdxA9+KFJjwwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDEMMAoGA1UEAxMDUjEyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEA2pgodK2+lP474B7i5Ut1qywSf+2nAzJ+Npfs6DGPpRONC5kuHs0BUT1M
    5ShuCVUxqqUiXXL0LQfCTUA83wEjuXg39RplMjTmhnGdBO+ECFu9AhqZ66YBAJpz
    kG2Pogeg0JfT2kVhgTU9FPnEwF9q3AuWGrCf4yrqvSrWmMebcas7dA8827JgvlpL
    Thjp2ypzXIlhZZ7+7Tymy05v5J75AEaz/xlNKmOzjmbGGIVwx1Blbzt05UiDDwhY
    XS0jnV6j/ujbAKHS9OMZTfLuevYnnuXNnC2i8n+cF63vEzc50bTILEHWhsDp7CH4
    WRt/uTp8n1wBnWIEwii9Cq08yhDsGwIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
    hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
    /wIBADAdBgNVHQ4EFgQUALUp8i2ObzHom0yteD763OkM0dIwHwYDVR0jBBgwFoAU
    ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
    hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
    A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
    AQELBQADggIBAI910AnPanZIZTKS3rVEyIV29BWEjAK/duuz8eL5boSoVpHhkkv3
    4eoAeEiPdZLj5EZ7G2ArIK+gzhTlRQ1q4FKGpPPaFBSpqV/xbUb5UlAXQOnkHn3m
    FVj+qYv87/WeY+Bm4sN3Ox8BhyaU7UAQ3LeZ7N1X01xxQe4wIAAE3JVLUCiHmZL+
    qoCUtgYIFPgcg350QMUIWgxPXNGEncT921ne7nluI02V8pLUmClqXOsCwULw+PVO
    ZCB7qOMxxMBoCUeL2Ll4oMpOSr5pJCpLN3tRA2s6P1KLs9TSrVhOk+7LX28NMUlI
    usQ/nxLJID0RhAeFtPjyOCOscQBA53+NRjSCak7P4A5jX7ppmkcJECL+S0i3kXVU
    y5Me5BbrU8973jZNv/ax6+ZK6TM8jWmimL6of6OrX7ZU6E2WqazzsFrLG3o2kySb
    zlhSgJ81Cl4tv3SbYiYXnJExKQvzf83DYotox3f0fwv7xln1A2ZLplCb0O+l/AK0
    YE0DS2FPxSAHi0iwMfW2nNHJrXcY3LLHD77gRgje4Eveubi2xxa+Nmk/hmhLdIET
    iVDFanoCrMVIpQ59XWHkzdFmoHXHBV7oibVjGSO7ULSQ7MJ1Nz51phuDJSgAIU7A
    0zrLnOrAj/dfrlEWRhCvAgbuwLZX1A2sjNjXoPOHbsPiy+lO1KF8/XY7
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAtWmtLsZdQBeRksqVNyq82C83nLcNnnsnUsa73/6GJIViYjq+
    6tTwC23pBqJSTL7/1wxVr7JNTsM93n3QncKdqs2Xy1S08x1XQ68xxQuKpSGYTWXi
    A6DT0TuT75fAs8N3ogOp0Cum5Ht3XHeE4OdJ7hHM5mT/fKbl022XV9L6IvNLX4BH
    A6B6ukKteWvvC6cf/soyaGr0qOqW687gop7OTP6LnUzwDEKLN5pPD4ak3lu9Df9u
    sZg9zpyIooq+znRPHIa7YOgiswQyOs01/Tkj9k0EZgi/x7KC1b4IN2VLWIa0uRqr
    fPDb9hkoWNycNVSGNmCtvuwKhvOE5u1gtcNfZQIDAQABAoIBAG1/ZJW4C271Ctvk
    RR5wQF3oWhPQdXrz8K9I3vt7gHIoxFJwDO5nKqBrbdygOzaxjnC5tDqBT6I7vGs/
    25xtbIc84uNKtJGNYy+qXksGBWBYn7oPxdTUzSUcZdWW7ixSzjHPLj9FKc39K/V2
    +pBZakk1G0zxJziQ8GWmX1QWNv7Cf41ccbGwx4jZOa00Au6QUnCSulN0kbcqSaML
    rRA5U/+IJf4zzDnckzWNneepXJvqvgsqsXZjW9TAxiIx7QyYJWZUoDoeRxQgtDtq
    lxnISBfOEbbTzf2GdaEEArx5Y1R+HmG0QPz1LRikeINu/1TIx0Z87kvL3YBYeWOn
    cca/Gj0CgYEAwy93vWoBLnYm1BTswiXNDnJxLT7QBIiL8MtUTnjGfKSuYmtFJ8Jm
    x+V3A5h02HXAjj+TXwvz4O0wrCmYBGGl9tK0ACZot1ZRnc0OjyghKQ6qZVRPl+Eh
    glqU1Om8AhvXXx13uekw0u5HUfSHN2eTysXjmNxCK1iPnS2v9GEAMssCgYEA7e+q
    hexdsxclKJVrDdfR0TAoXDzaSBj981GfZonegSQb3CQzqFVmEzt0rfmiQeZpypEx
    /+nzo6+4r+vxZLrv8iLqUScoOAG6BsAB4Edux2wOvYGVMaa9Zy1QxRMeIifHSxle
    22+pu8krkpu1WCWDt4QOv1aOqA+DmUKb15QVAI8CgYAogdRm0fYWz1x1jTYpgLDS
    u7tzOWLwXeo0+e2wL2559a9fK4X5n2W3PI77hwtQ1Pc2TklmY1OkrXT5ddRfrGhG
    FipXEaGP0vEzP5gy65AeNjX0u4+dJJLQu73BhhSHl4GV8sajJZsFW4AfqRDa1bsd
    TP5T/foZhtKfOxkWLX9eCwKBgQCrzFj7yeb94MBbxUc+/43n1TXPI8EYPbNfdJf7
    maCm7kOPeDQ0XzUMvelJlO2rV4sbUCsh9PKORdq8a0goyzFlTACUCAnqJpUDOrAg
    GHPMWiFqg54N867eSMIBCgS/9KjZeMAdAUs049QqT3No6e1pHFjpnr3yawFCL+4G
    gk2H0QKBgEIG1V6TZCN7GH3Q73wHK8Rc2airhg5aYvSL2UxHDU/OwrhzfauRS++m
    1fy1/rboi3cd9K0fjc/OhbTTXw1LKW8K2MOUKk8gc+mCWtm9ehwI15v1IXeyRZu/
    YjWdysc3TQj/XuNZKDgQBjkACuVyV6TTbrqtUMuUiGnMNJfvgTfL
    -----END RSA PRIVATE KEY-----
