apiVersion: v1
kind: Secret
metadata:
  name: local-lco-earth-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE+zCCA+OgAwIBAgISBb+/1WF7nKO1LVhbYYXUKPMBMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNZUjIwHhcNMjYwOTA4MTIzNzI0WhcNMjYxMjA3MTIzNzIzWjAcMRowGAYDVQQD
    DBEqLmxvY2FsLmxjby5lYXJ0aDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBALVprS7GXUAXkZLKlTcqvNgvN5y3DZ57J1LGu9/+hiSFYmI6vurU8Att6Qai
    Uky+/9cMVa+yTU7DPd590J3CnarNl8tUtPMdV0OvMcULiqUhmE1l4gOg09E7k++X
    wLPDd6IDqdArpuR7d1x3hODnSe4RzOZk/3ym5dNtl1fS+iLzS1+ARwOgerpCrXlr
    7wunH/7KMmhq9KjqluvO4KKezkz+i51M8AxCizeaTw+GpN5bvQ3/brGYPc6ciKKK
    vs50TxyGu2DoIrMEMjrNNf05I/ZNBGYIv8eygtW+CDdlS1iGtLkaq3zw2/YZKFjc
    nDVUhjZgrb7sCobzhObtYLXDX2UCAwEAAaOCAh4wggIaMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTi
    FCw6gnmOlxDaRagTph/jyR1ScTAfBgNVHSMEGDAWgBRAFS0mee0yIJ7fmnId1jIf
    gQyBDDAzBggrBgEFBQcBAQQnMCUwIwYIKwYBBQUHMAKGF2h0dHA6Ly95cjIuaS5s
    ZW5jci5vcmcvMBwGA1UdEQQVMBOCESoubG9jYWwubGNvLmVhcnRoMBMGA1UdIAQM
    MAowCAYGZ4EMAQIBMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly95cjIuYy5sZW5j
    ci5vcmcvMi5jcmwwggEMBgorBgEEAdZ5AgQCBIH9BIH6APgAdgDLOPcViXyEoURf
    W8Hd+8lu8ppZzUcKaQWFsMsUwxRY5wAAAaCBO3vZAAAEAwBHMEUCIQCcpn4I9NH0
    5RkyPzT/GCdp5Pn6MplE6dMerFXzCjiaNAIgFhHSIgf5H9Bxo6tMUl0TTwQFyX3F
    6kvoHXJQHBJs4N4AfgCoJsvjCsY1EkZTP+Bl8U8Z2W4ZCBPEHdlteQCzEjxVJwAA
    AaCBO36pAAgAAAUALrYwxwQDAEcwRQIhAMMLSqBTDNq1VSHDDZ5/19eYeW4DLD9h
    jIMN37vi5NUGAiA9roaNhlO7Wr++Z56RJTdHPZXEx7x0/7GvYmLmCvp1jTANBgkq
    hkiG9w0BAQsFAAOCAQEAvY776kJnGs6JYzoQzgzhLSm0TKmEfBMUEFTJIhicDecv
    cg3cLRz7Ab+fuesDfzwF8xjG0Jz1hiVQEWhs3ySk/1LpZCOec9NEKD/M2os3abec
    3pq1b9HxzEAR0NlSD/5M0vYRiVxwPNCcrBp10IzBSWqI0gbO2c62LUsPpzI71AqC
    VDai+P6cifXN27z/AZPQKg0Gvro2bfb1nkGnfVA6LD/1GJ/v4OoIotwbUqloRFT0
    zjjUAUocMGMWcOeTYeIRf0BV0zEyYWOBuyx0GirNqRo3VZ+wvHA5YwDW7Gs+UbmN
    SDZ0SdMZLGYDbELHVzo704nTTiZcZ60X0f1kBKV+BA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIE2jCCAsKgAwIBAgIQTr0klH4k05SALYSlL9WzGTANBgkqhkiG9w0BAQsFADAu
    MQswCQYDVQQGEwJVUzENMAsGA1UEChMESVNSRzEQMA4GA1UEAxMHUm9vdCBZUjAe
    Fw0yNTA5MDMwMDAwMDBaFw0yODA5MDIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYw
    FAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQDEwNZUjIwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDZ0LxwBppqh84luqMerV/eeL/fXQ7mLQQv1Lnp
    WKZbyvGpx6wh6AfnslAnF6ewTkcHA+gSOoBvm3Dfm06AuGiF+KRut4fAcowqnAQQ
    CW98+QPP/eOv/wug7Iyk4NkOxf2I6g2f55T6nJoOTLFcukeRq80JGQEYan+dPFr9
    OGUgQK2hGKgNkW87pappsOAuUJcroYhRt5uUis4qaZireiseu32gzDJNBAiKtsvd
    6HX4v25bpkRNcS/B/Gtc9kVbUpD+2PLPxdei3Tim55k4tfAEXwD2qyiPTxrTNq6l
    N+AMr5g2c1dNqkOTwjxeV6L5lpP1rGiYvLnRaPlOqyZRPW+5AgMBAAGjge4wgesw
    DgYDVR0PAQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBIGA1UdEwEB/wQI
    MAYBAf8CAQAwHQYDVR0OBBYEFEAVLSZ57TIgnt+ach3WMh+BDIEMMB8GA1UdIwQY
    MBaAFN7nW2DQIm1AKH0/DQH+pLVStFGUMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEF
    BQcwAoYWaHR0cDovL3lyLmkubGVuY3Iub3JnLzATBgNVHSAEDDAKMAgGBmeBDAEC
    ATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veXIuYy5sZW5jci5vcmcvMA0GCSqG
    SIb3DQEBCwUAA4ICAQB0ZUQWZ9/Yn9COEpo+JfecMnB0h0vwDm/M66IqXqw3LoaL
    mx9lZvRTeDIS67PUeI3yCA2W6PKRD0/FE/G57lOmS+Xy5AaaL00ICGOqjNcCaMWW
    8o8nevHOd4i4lqgtznE/28QwlcdJyF8yBiWHpnyjhEpmNWJURgOCOg2xpwRMBCsj
    MScqYPtOhBeuYQvSwAEeTML2Ukh6uGuX4E14q65Ja8cdjF5bAldnP1eE4FBaAwsZ
    G2fOqqrKV03Y85Nw2btedP1AtliQuJZs/Jo/gXxXdc7LrH3McgnpnbTiAncX7yES
    hP6kzQejllqMCIt52HOjxDGWafS7Xw+DKwqmH+Eqy8dcbOuag/1AYlQoKNVK3F5q
    Hh6tEDiMqQcLIibGKteE6iHo4A/bIScbzrhXUYuism42ZYzmc48FMVIH3qy4L84E
    TdAH2gtxw0PAhvRVXp8HP7wfngpzsN/8xOTpeRSbM4+Qbc56G6+Bifmv6sk1ieQb
    NA3wJdl4DDUuQSV8hBgx6zoI1ZSGORprDFux7c6rhc77QZMSRrEgomBeklervEve
    86ylWmZ3WWHV6RLMi8xNvjd71r4EPIGgY7BZU/VPBkq+uA7Gb6mbJnFgV43uh3xy
    LRFgxIAphIukwTGSMZZR+AI+Qnp0BYTWovHXozOf3H8r6hozEoT02JHn0AeTfA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIF9DCCA9ygAwIBAgIRAPJLbRf52a18scn+p4eCaZ8wDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjYwNTEzMDAwMDAw
    WhcNMzIwOTAyMjM1OTU5WjAuMQswCQYDVQQGEwJVUzENMAsGA1UEChMESVNSRzEQ
    MA4GA1UEAxMHUm9vdCBZUjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ANvGJnN78CTJdWL3+eGfsLN5TrNBJs+VH9hRXqRbwxu9sGNiB0BD1fcOxbSUQCJI
    M1xE13Db+5Cw1w0s0EBYsvuIP/6joF0w8cuImbgR1OGgYbSQ4OpzI+DG8SGuTlcE
    873OCS+kh3srlo6vl43M5OJg4Aeo1sfHp6kTJDoIiFBNJAY+OKfX/FUvYKuhjT+n
    o49lmqmupSBI5PkBQiqrEGtWU5uxU/cQWHGu8jSjFBznZqvbNPLMXMLFxCb3WTfr
    JBXXjqvWG+v4bjzxjjeAtOlU7qarRDvNOyAuQYLln904M+faKx8hnLCpJ15ZqaEg
    cNlY+9MMWcC5yvL2A2j3l9+2buggZX+dOE91zYmIdawTvSZuVvlbRrAlLxIB6pwM
    BjneXCjYQ8+3BCCjssbSNpZU3hTcBDdhfAlEDlYr6pEatnMdmDT5BqnKC92bd0Eh
    M1fbLHioLccLCuievT8ZkPhZrq7Mii7gNXAcUEAR8+lzYal+9zTg7C5DALyVOeG/
    CqfRAMn1KSHCR0NSA6P8tn/mGRlnCct5rtVCLnVySVpU6H1qGg3DgTOuskf8eahT
    MiYbI5ezPJmO5ertalskQ1utp74+eDy92PI4ftHKTbq9IWhH4YZKh3WnJEIt+oQv
    lYZbY8tpEroKrFB6PFGzrJIDRyts4HqvuH52RFj2zv/BAgMBAAGjgeswgegwDgYD
    VR0PAQH/BAQDAgEGMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMB
    Af8wHQYDVR0OBBYEFN7nW2DQIm1AKH0/DQH+pLVStFGUMB8GA1UdIwQYMBaAFHm0
    WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcwAoYW
    aHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAEDDAKMAgGBmeBDAECATAnBgNV
    HR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5jci5vcmcvMA0GCSqGSIb3DQEB
    CwUAA4ICAQA8spSI95KKfn2W6GMmDpHBJSPaLbsS3W93cijJCRCYAc1fsJgL1FIL
    7C0C9ecPOdcwB2fi0Dk2p94j9iTJCxmt5CFSKLRWwnXT2MMSXexVxqoVB79BdWPx
    VXETkVme/qYSAuKVHh5Ps+5BixgmwS1JkjSAc+MfrUbNssVEEnH0aEiAh+rotXAV
    JSP/Ye7LJPEwD9DWG72vVWbhAcuOf5OLjz57Ctk7MgQHynZ7+PlHJtajroCaIbtC
    r6tcZZaAwUQm+jQyeWdV+2hv9deOYFmKeQyjjcSrN5Nadrw+L9DZJLbA1HqeNvLh
    BgqpP0fvJq2N6EtD574N6eMI7uMsJTnji2UDz9el5XLSv9fqJMuDQtYVb2oTNoKp
    oUqhxPVC0aq4eG5MESaIdn8b5ZGSSeAJLMHXljEdlNza+ncfkviXk1POLnnFdvx8
    /gk6M374WbLWFXw8N141B/Rl/tINGfl1TxOIiqtiMYkL02RSGb1kq34BL9NPP27z
    RGMuHGnzS3hFIrRTfKxrzUZ9RzQWzEG3K6fJ3r2nqSltkeytis9DIBoFY9VmVyjL
    M71DMi+y1+TRSJVClEMwvA4yL++7q9XZx5r5wBRWB4kQTKH5qyoZnDw7iiuh1lID
    yDFx8r7i9vIJU5HS3moZLkYWAOilMaV9N56A9Bgb6dNcHkvg3NoaYA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAtWmtLsZdQBeRksqVNyq82C83nLcNnnsnUsa73/6GJIViYjq+
    6tTwC23pBqJSTL7/1wxVr7JNTsM93n3QncKdqs2Xy1S08x1XQ68xxQuKpSGYTWXi
    A6DT0TuT75fAs8N3ogOp0Cum5Ht3XHeE4OdJ7hHM5mT/fKbl022XV9L6IvNLX4BH
    A6B6ukKteWvvC6cf/soyaGr0qOqW687gop7OTP6LnUzwDEKLN5pPD4ak3lu9Df9u
    sZg9zpyIooq+znRPHIa7YOgiswQyOs01/Tkj9k0EZgi/x7KC1b4IN2VLWIa0uRqr
    fPDb9hkoWNycNVSGNmCtvuwKhvOE5u1gtcNfZQIDAQABAoIBAG1/ZJW4C271Ctvk
    RR5wQF3oWhPQdXrz8K9I3vt7gHIoxFJwDO5nKqBrbdygOzaxjnC5tDqBT6I7vGs/
    25xtbIc84uNKtJGNYy+qXksGBWBYn7oPxdTUzSUcZdWW7ixSzjHPLj9FKc39K/V2
    +pBZakk1G0zxJziQ8GWmX1QWNv7Cf41ccbGwx4jZOa00Au6QUnCSulN0kbcqSaML
    rRA5U/+IJf4zzDnckzWNneepXJvqvgsqsXZjW9TAxiIx7QyYJWZUoDoeRxQgtDtq
    lxnISBfOEbbTzf2GdaEEArx5Y1R+HmG0QPz1LRikeINu/1TIx0Z87kvL3YBYeWOn
    cca/Gj0CgYEAwy93vWoBLnYm1BTswiXNDnJxLT7QBIiL8MtUTnjGfKSuYmtFJ8Jm
    x+V3A5h02HXAjj+TXwvz4O0wrCmYBGGl9tK0ACZot1ZRnc0OjyghKQ6qZVRPl+Eh
    glqU1Om8AhvXXx13uekw0u5HUfSHN2eTysXjmNxCK1iPnS2v9GEAMssCgYEA7e+q
    hexdsxclKJVrDdfR0TAoXDzaSBj981GfZonegSQb3CQzqFVmEzt0rfmiQeZpypEx
    /+nzo6+4r+vxZLrv8iLqUScoOAG6BsAB4Edux2wOvYGVMaa9Zy1QxRMeIifHSxle
    22+pu8krkpu1WCWDt4QOv1aOqA+DmUKb15QVAI8CgYAogdRm0fYWz1x1jTYpgLDS
    u7tzOWLwXeo0+e2wL2559a9fK4X5n2W3PI77hwtQ1Pc2TklmY1OkrXT5ddRfrGhG
    FipXEaGP0vEzP5gy65AeNjX0u4+dJJLQu73BhhSHl4GV8sajJZsFW4AfqRDa1bsd
    TP5T/foZhtKfOxkWLX9eCwKBgQCrzFj7yeb94MBbxUc+/43n1TXPI8EYPbNfdJf7
    maCm7kOPeDQ0XzUMvelJlO2rV4sbUCsh9PKORdq8a0goyzFlTACUCAnqJpUDOrAg
    GHPMWiFqg54N867eSMIBCgS/9KjZeMAdAUs049QqT3No6e1pHFjpnr3yawFCL+4G
    gk2H0QKBgEIG1V6TZCN7GH3Q73wHK8Rc2airhg5aYvSL2UxHDU/OwrhzfauRS++m
    1fy1/rboi3cd9K0fjc/OhbTTXw1LKW8K2MOUKk8gc+mCWtm9ehwI15v1IXeyRZu/
    YjWdysc3TQj/XuNZKDgQBjkACuVyV6TTbrqtUMuUiGnMNJfvgTfL
    -----END RSA PRIVATE KEY-----
